user_city_preferences:
  type: config_object
  label: 'User City Preferences'
  mapping:
    uid:
      type: integer
      label: 'User ID'
    city:
      type: string
      label: 'Selected City'
  constraints:
    primary:
      type: primary_key
      fields:
        - uid
