<?php

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function custom_config_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'menu_block:social-media') {
    $entityTypeManager = \Drupal::service('entity_type.manager');
    $config = $entityTypeManager->getStorage('config_pages')->load('social_links_text');
    $field_social_media = $config->get('field_social_media')->value;
    $variables['social_media_text'] = $field_social_media;
  }
}
